language: generic
dist: bionic
env:
  global:
    - TEX_MAIN=main.tex

notifications:
  email: false

install:
  - source .travis/texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: cd $TRAVIS_BUILD_DIR/
script:
  # texliveonfly will try to download packages automatically
  - texliveonfly --compiler=xelatex --arguments="-shell-escape" --terminal_only $TEX_MAIN
  # latexmk will automatically handle bibtex and references
  - latexmk -pdf -xelatex $TEX_MAIN

deploy:
  provider: releases
  api_key:
    secure: GITHUB_RELEASE_TOKEN
  file_glob: true
  file:
    - "./*.pdf"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
